### ISSUE TITLE
Overlapping formatting impacts later formatting correctness

### ISSUE THREAD

**Issue by GroveJay** [ReagentX/imessage-exporter#567]
Issue: Overlapping formatting seems to cause issue with formatting correctness later in a message.

Example reproduction steps:
1. Construct a message with enough text to have multiple overlapping and non overlapping styles (eg. `0123456789 Bold Italics Underline Strikethrough Big Small Shake Nod Explode Ripple Bloom Jitter`)
2. Add overlapping styles to part of the message (eg. `0123456` underlined and `56789` strikethrough)
3. Add non-overlapping styles to a later part of the message (eg. `Bold` bold, `Italics` bold and italics, `Underline` bold, italics, and underlined, `Strikethrough` bold, italics, underlined, and strikethrough.
4. (optional) Add other text effects to the additional words (eg. `Big` big effect, etc. These cannot be applied overlapping)

Actual result:
The text ranges are not properly styled and later ranges are not styled at all. 
<img width="559" alt="Image" src="https://github.com/user-attachments/assets/4d262b15-2f04-42fd-a769-d7af786f7a90" />
<img width="348" alt="Image" src="https://github.com/user-attachments/assets/49cca711-3166-4e5f-bd95-217087e6de40" />

Expected result:
Screenshot from Messages
<img width="322" alt="Image" src="https://github.com/user-attachments/assets/e8184673-ba29-4c8c-b51a-4d7ce8d94bda" />

**Comment by GroveJay** [comment]
Attached is the `attributedBody` (had to add `.txt` file extension to make github accept the upload)
[35123-attributedBody.txt](https://github.com/user-attachments/files/20854594/35123-attributedBody.txt)

**Comment by ReagentX** [comment]
Yeah, I found this as well. I've written a separate, soon-to-be-published crate that properly resolves `typedstream`'s structure that will be published soon and will, when integrated, resolve this issue.

The problem is that a split `NSURL` becomes misaligned in the existing `typedstream` parser, leading to subsequent lookups in the `BubbleComponent` assembler not pointing to the correct things.

**Comment by ReagentX** [comment]
Your sample stream is parsed as:

```
  Group:
    Object: "NSMutableString"
      Group:
        Primitive: String("0123456789\nBold Italics Underline Strikethrough\u{a0}\u{a0}Big Small Shake Nod Explode Ripple Bloom Jitter")
  Group:
    Primitive: SignedInteger(1)
    Primitive: UnsignedInteger(5)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(5)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextUnderlineAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMLinkAttributeName")
      Group:
        Object: "NSURL"
          Group:
            Primitive: SignedInteger(0)
          Group:
            Object: "NSString"
              Group:
                Primitive: String("tel:0123456789")
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMPhoneNumberAttributeName")
      Group:
        Object: "NSData"
          Group:
            Primitive: SignedInteger(649)
          Group:
            Primitive: Array([98, 112, 108, 105, 115, 116, 48, 48, 212, 1, 2, 3, 4, 5, 6, 7, 12, 88, 36, 118, 101, 114, 115, 105, 111, 110, 89, 36, 97, 114, 99, 104, 105, 118, 101, 114, 84, 36, 116, 111, 112, 88, 36, 111, 98, 106, 101, 99, 116, 115, 18, 0, 1, 134, 160, 95, 16, 15, 78, 83, 75, 101, 121, 101, 100, 65, 114, 99, 104, 105, 118, 101, 114, 210, 8, 9, 10, 11, 87, 118, 101, 114, 115, 105, 111, 110, 89, 100, 100, 45, 114, 101, 115, 117, 108, 116, 128, 16, 128, 1, 175, 16, 17, 13, 14, 28, 36, 37, 38, 44, 45, 46, 51, 57, 61, 62, 63, 66, 69, 73, 85, 36, 110, 117, 108, 108, 215, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 26, 82, 77, 83, 86, 36, 99, 108, 97, 115, 115, 82, 65, 82, 81, 84, 81, 80, 82, 83, 82, 82, 86, 78, 128, 6, 128, 15, 128, 2, 128, 7, 16, 1, 128, 8, 212, 29, 30, 31, 16, 32, 33, 34, 35, 95, 16, 18, 78, 83, 46, 114, 97, 110, 103, 101, 118, 97, 108, 46, 108, 101, 110, 103, 116, 104, 95, 16, 20, 78, 83, 46, 114, 97, 110, 103, 101, 118, 97, 108, 46, 108, 111, 99, 97, 116, 105, 111, 110, 90, 78, 83, 46, 115, 112, 101, 99, 105, 97, 108, 128, 3, 128, 4, 16, 4, 128, 5, 16, 10, 16, 0, 210, 39, 40, 41, 42, 90, 36, 99, 108, 97, 115, 115, 110, 97, 109, 101, 88, 36, 99, 108, 97, 115, 115, 101, 115, 87, 78, 83, 86, 97, 108, 117, 101, 162, 41, 43, 88, 78, 83, 79, 98, 106, 101, 99, 116, 90, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 91, 80, 104, 111, 110, 101, 78, 117, 109, 98, 101, 114, 210, 47, 16, 48, 50, 90, 78, 83, 46, 111, 98, 106, 101, 99, 116, 115, 161, 49, 128, 9, 128, 14, 215, 15, 16, 17, 18, 19, 20, 21, 52, 23, 54, 55, 26, 56, 26, 128, 11, 128, 15, 128, 10, 128, 12, 128, 13, 212, 29, 30, 31, 16, 32, 33, 34, 35, 128, 3, 128, 4, 128, 5, 90, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 85, 86, 97, 108, 117, 101, 210, 47, 16, 64, 50, 160, 128, 14, 210, 39, 40, 67, 68, 87, 78, 83, 65, 114, 114, 97, 121, 162, 67, 43, 210, 39, 40, 70, 71, 95, 16, 15, 68, 68, 83, 99, 97, 110, 110, 101, 114, 82, 101, 115, 117, 108, 116, 162, 72, 43, 95, 16, 15, 68, 68, 83, 99, 97, 110, 110, 101, 114, 82, 101, 115, 117, 108, 116, 16, 1, 0, 8, 0, 17, 0, 26, 0, 36, 0, 41, 0, 50, 0, 55, 0, 73, 0, 78, 0, 86, 0, 96, 0, 98, 0, 100, 0, 120, 0, 126, 0, 141, 0, 144, 0, 151, 0, 154, 0, 156, 0, 158, 0, 161, 0, 164, 0, 166, 0, 168, 0, 170, 0, 172, 0, 174, 0, 176, 0, 185, 0, 206, 0, 229, 0, 240, 0, 242, 0, 244, 0, 246, 0, 248, 0, 250, 0, 252, 1, 1, 1, 12, 1, 21, 1, 29, 1, 32, 1, 41, 1, 52, 1, 64, 1, 69, 1, 80, 1, 82, 1, 84, 1, 86, 1, 101, 1, 103, 1, 105, 1, 107, 1, 109, 1, 111, 1, 120, 1, 122, 1, 124, 1, 126, 1, 137, 1, 143, 1, 148, 1, 149, 1, 151, 1, 156, 1, 164, 1, 167, 1, 172, 1, 190, 1, 193, 1, 211, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 213])
  Group:
    Primitive: SignedInteger(2)
    Primitive: UnsignedInteger(2)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(6)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextUnderlineAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMPhoneNumberAttributeName")
      Group:
        Object: "NSData"
          Group:
            Primitive: SignedInteger(649)
          Group:
            Primitive: Array([98, 112, 108, 105, 115, 116, 48, 48, 212, 1, 2, 3, 4, 5, 6, 7, 12, 88, 36, 118, 101, 114, 115, 105, 111, 110, 89, 36, 97, 114, 99, 104, 105, 118, 101, 114, 84, 36, 116, 111, 112, 88, 36, 111, 98, 106, 101, 99, 116, 115, 18, 0, 1, 134, 160, 95, 16, 15, 78, 83, 75, 101, 121, 101, 100, 65, 114, 99, 104, 105, 118, 101, 114, 210, 8, 9, 10, 11, 87, 118, 101, 114, 115, 105, 111, 110, 89, 100, 100, 45, 114, 101, 115, 117, 108, 116, 128, 16, 128, 1, 175, 16, 17, 13, 14, 28, 36, 37, 38, 44, 45, 46, 51, 57, 61, 62, 63, 66, 69, 73, 85, 36, 110, 117, 108, 108, 215, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 26, 82, 77, 83, 86, 36, 99, 108, 97, 115, 115, 82, 65, 82, 81, 84, 81, 80, 82, 83, 82, 82, 86, 78, 128, 6, 128, 15, 128, 2, 128, 7, 16, 1, 128, 8, 212, 29, 30, 31, 16, 32, 33, 34, 35, 95, 16, 18, 78, 83, 46, 114, 97, 110, 103, 101, 118, 97, 108, 46, 108, 101, 110, 103, 116, 104, 95, 16, 20, 78, 83, 46, 114, 97, 110, 103, 101, 118, 97, 108, 46, 108, 111, 99, 97, 116, 105, 111, 110, 90, 78, 83, 46, 115, 112, 101, 99, 105, 97, 108, 128, 3, 128, 4, 16, 4, 128, 5, 16, 10, 16, 0, 210, 39, 40, 41, 42, 90, 36, 99, 108, 97, 115, 115, 110, 97, 109, 101, 88, 36, 99, 108, 97, 115, 115, 101, 115, 87, 78, 83, 86, 97, 108, 117, 101, 162, 41, 43, 88, 78, 83, 79, 98, 106, 101, 99, 116, 90, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 91, 80, 104, 111, 110, 101, 78, 117, 109, 98, 101, 114, 210, 47, 16, 48, 50, 90, 78, 83, 46, 111, 98, 106, 101, 99, 116, 115, 161, 49, 128, 9, 128, 14, 215, 15, 16, 17, 18, 19, 20, 21, 52, 23, 54, 55, 26, 56, 26, 128, 11, 128, 15, 128, 10, 128, 12, 128, 13, 212, 29, 30, 31, 16, 32, 33, 34, 35, 128, 3, 128, 4, 128, 5, 90, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 85, 86, 97, 108, 117, 101, 210, 47, 16, 64, 50, 160, 128, 14, 210, 39, 40, 67, 68, 87, 78, 83, 65, 114, 114, 97, 121, 162, 67, 43, 210, 39, 40, 70, 71, 95, 16, 15, 68, 68, 83, 99, 97, 110, 110, 101, 114, 82, 101, 115, 117, 108, 116, 162, 72, 43, 95, 16, 15, 68, 68, 83, 99, 97, 110, 110, 101, 114, 82, 101, 115, 117, 108, 116, 16, 1, 0, 8, 0, 17, 0, 26, 0, 36, 0, 41, 0, 50, 0, 55, 0, 73, 0, 78, 0, 86, 0, 96, 0, 98, 0, 100, 0, 120, 0, 126, 0, 141, 0, 144, 0, 151, 0, 154, 0, 156, 0, 158, 0, 161, 0, 164, 0, 166, 0, 168, 0, 170, 0, 172, 0, 174, 0, 176, 0, 185, 0, 206, 0, 229, 0, 240, 0, 242, 0, 244, 0, 246, 0, 248, 0, 250, 0, 252, 1, 1, 1, 12, 1, 21, 1, 29, 1, 32, 1, 41, 1, 52, 1, 64, 1, 69, 1, 80, 1, 82, 1, 84, 1, 86, 1, 101, 1, 103, 1, 105, 1, 107, 1, 109, 1, 111, 1, 120, 1, 122, 1, 124, 1, 126, 1, 137, 1, 143, 1, 148, 1, 149, 1, 151, 1, 156, 1, 164, 1, 167, 1, 172, 1, 190, 1, 193, 1, 211, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 213])
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextStrikethroughAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMLinkAttributeName")
      Group:
        Object: "NSURL"
          Group:
            Primitive: SignedInteger(0)
          Group:
            Object: "NSString"
              Group:
                Primitive: String("tel:0123456789")
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
  Group:
    Primitive: SignedInteger(3)
    Primitive: UnsignedInteger(3)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(5)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextStrikethroughAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMLinkAttributeName")
      Group:
        Object: "NSURL"
          Group:
            Primitive: SignedInteger(0)
          Group:
            Object: "NSString"
              Group:
                Primitive: String("tel:0123456789")
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMPhoneNumberAttributeName")
      Group:
        Object: "NSData"
          Group:
            Primitive: SignedInteger(649)
          Group:
            Primitive: Array([98, 112, 108, 105, 115, 116, 48, 48, 212, 1, 2, 3, 4, 5, 6, 7, 12, 88, 36, 118, 101, 114, 115, 105, 111, 110, 89, 36, 97, 114, 99, 104, 105, 118, 101, 114, 84, 36, 116, 111, 112, 88, 36, 111, 98, 106, 101, 99, 116, 115, 18, 0, 1, 134, 160, 95, 16, 15, 78, 83, 75, 101, 121, 101, 100, 65, 114, 99, 104, 105, 118, 101, 114, 210, 8, 9, 10, 11, 87, 118, 101, 114, 115, 105, 111, 110, 89, 100, 100, 45, 114, 101, 115, 117, 108, 116, 128, 16, 128, 1, 175, 16, 17, 13, 14, 28, 36, 37, 38, 44, 45, 46, 51, 57, 61, 62, 63, 66, 69, 73, 85, 36, 110, 117, 108, 108, 215, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 26, 82, 77, 83, 86, 36, 99, 108, 97, 115, 115, 82, 65, 82, 81, 84, 81, 80, 82, 83, 82, 82, 86, 78, 128, 6, 128, 15, 128, 2, 128, 7, 16, 1, 128, 8, 212, 29, 30, 31, 16, 32, 33, 34, 35, 95, 16, 18, 78, 83, 46, 114, 97, 110, 103, 101, 118, 97, 108, 46, 108, 101, 110, 103, 116, 104, 95, 16, 20, 78, 83, 46, 114, 97, 110, 103, 101, 118, 97, 108, 46, 108, 111, 99, 97, 116, 105, 111, 110, 90, 78, 83, 46, 115, 112, 101, 99, 105, 97, 108, 128, 3, 128, 4, 16, 4, 128, 5, 16, 10, 16, 0, 210, 39, 40, 41, 42, 90, 36, 99, 108, 97, 115, 115, 110, 97, 109, 101, 88, 36, 99, 108, 97, 115, 115, 101, 115, 87, 78, 83, 86, 97, 108, 117, 101, 162, 41, 43, 88, 78, 83, 79, 98, 106, 101, 99, 116, 90, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 91, 80, 104, 111, 110, 101, 78, 117, 109, 98, 101, 114, 210, 47, 16, 48, 50, 90, 78, 83, 46, 111, 98, 106, 101, 99, 116, 115, 161, 49, 128, 9, 128, 14, 215, 15, 16, 17, 18, 19, 20, 21, 52, 23, 54, 55, 26, 56, 26, 128, 11, 128, 15, 128, 10, 128, 12, 128, 13, 212, 29, 30, 31, 16, 32, 33, 34, 35, 128, 3, 128, 4, 128, 5, 90, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 85, 86, 97, 108, 117, 101, 210, 47, 16, 64, 50, 160, 128, 14, 210, 39, 40, 67, 68, 87, 78, 83, 65, 114, 114, 97, 121, 162, 67, 43, 210, 39, 40, 70, 71, 95, 16, 15, 68, 68, 83, 99, 97, 110, 110, 101, 114, 82, 101, 115, 117, 108, 116, 162, 72, 43, 95, 16, 15, 68, 68, 83, 99, 97, 110, 110, 101, 114, 82, 101, 115, 117, 108, 116, 16, 1, 0, 8, 0, 17, 0, 26, 0, 36, 0, 41, 0, 50, 0, 55, 0, 73, 0, 78, 0, 86, 0, 96, 0, 98, 0, 100, 0, 120, 0, 126, 0, 141, 0, 144, 0, 151, 0, 154, 0, 156, 0, 158, 0, 161, 0, 164, 0, 166, 0, 168, 0, 170, 0, 172, 0, 174, 0, 176, 0, 185, 0, 206, 0, 229, 0, 240, 0, 242, 0, 244, 0, 246, 0, 248, 0, 250, 0, 252, 1, 1, 1, 12, 1, 21, 1, 29, 1, 32, 1, 41, 1, 52, 1, 64, 1, 69, 1, 80, 1, 82, 1, 84, 1, 86, 1, 101, 1, 103, 1, 105, 1, 107, 1, 109, 1, 111, 1, 120, 1, 122, 1, 124, 1, 126, 1, 137, 1, 143, 1, 148, 1, 149, 1, 151, 1, 156, 1, 164, 1, 167, 1, 172, 1, 190, 1, 193, 1, 211, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 74, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 213])
  Group:
    Primitive: SignedInteger(4)
    Primitive: UnsignedInteger(6)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(3)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextBoldAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
  Group:
    Primitive: SignedInteger(5)
    Primitive: UnsignedInteger(8)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(4)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextBoldAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextItalicAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
  Group:
    Primitive: SignedInteger(6)
    Primitive: UnsignedInteger(10)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(5)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextBoldAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextUnderlineAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextItalicAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
  Group:
    Primitive: SignedInteger(7)
    Primitive: UnsignedInteger(13)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(6)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextItalicAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextBoldAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextStrikethroughAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextUnderlineAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(1)
  Group:
    Primitive: SignedInteger(8)
    Primitive: UnsignedInteger(2)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(2)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
  Group:
    Primitive: SignedInteger(9)
    Primitive: UnsignedInteger(4)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(3)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextEffectAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(5)
  Group:
    Primitive: SignedInteger(10)
    Primitive: UnsignedInteger(5)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(3)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextEffectAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(11)
  Group:
    Primitive: SignedInteger(8)
    Primitive: UnsignedInteger(1)
  Group:
    Primitive: SignedInteger(11)
    Primitive: UnsignedInteger(5)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(3)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextEffectAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(9)
  Group:
    Primitive: SignedInteger(8)
    Primitive: UnsignedInteger(1)
  Group:
    Primitive: SignedInteger(12)
    Primitive: UnsignedInteger(3)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(3)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextEffectAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(8)
  Group:
    Primitive: SignedInteger(8)
    Primitive: UnsignedInteger(1)
  Group:
    Primitive: SignedInteger(13)
    Primitive: UnsignedInteger(7)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(3)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextEffectAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(12)
  Group:
    Primitive: SignedInteger(8)
    Primitive: UnsignedInteger(1)
  Group:
    Primitive: SignedInteger(14)
    Primitive: UnsignedInteger(6)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(3)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextEffectAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(4)
  Group:
    Primitive: SignedInteger(8)
    Primitive: UnsignedInteger(1)
  Group:
    Primitive: SignedInteger(15)
    Primitive: UnsignedInteger(5)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(3)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextEffectAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(6)
  Group:
    Primitive: SignedInteger(8)
    Primitive: UnsignedInteger(1)
  Group:
    Primitive: SignedInteger(16)
    Primitive: UnsignedInteger(6)
  Group:
    Object: "NSDictionary"
      Group:
        Primitive: SignedInteger(3)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMBaseWritingDirectionAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(-1)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMMessagePartAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(0)
      Group:
        Object: "NSString"
          Group:
            Primitive: String("__kIMTextEffectAttributeName")
      Group:
        Object: "NSNumber"
          Group:
            Primitive: SignedInteger(10)
```

And the resultant `BubbleComponent`:

```
vec![BubbleComponent::Text(vec![
    TextAttributes {
        start: 0,
        end: 5,
        effects: vec![
            TextEffect::Link("tel:0123456789".to_string()),
            TextEffect::Styles(vec![Style::Underline]),
        ],
    },
    TextAttributes {
        start: 5,
        end: 7,
        effects: vec![
            TextEffect::Link("tel:0123456789".to_string()),
            TextEffect::Styles(vec![Style::Underline, Style::Strikethrough]),
        ],
    },
    TextAttributes {
        start: 7,
        end: 10,
        effects: vec![
            TextEffect::Link("tel:0123456789".to_string()),
            TextEffect::Styles(vec![Style::Strikethrough]),
        ],
    },
    TextAttributes {
        start: 10,
        end: 16,
        effects: vec![TextEffect::Styles(vec![Style::Bold])],
    },
    TextAttributes {
        start: 16,
        end: 24,
        effects: vec![TextEffect::Styles(vec![Style::Bold, Style::Italic])],
    },
    TextAttributes {
        start: 24,
        end: 34,
        effects: vec![TextEffect::Styles(vec![
            Style::Bold,
            Style::Underline,
            Style::Italic,
        ])],
    },
    TextAttributes {
        start: 34,
        end: 47,
        effects: vec![TextEffect::Styles(vec![
            Style::Italic,
            Style::Bold,
            Style::Strikethrough,
            Style::Underline,
        ])],
    },
    TextAttributes {
        start: 47,
        end: 51,
        effects: vec![TextEffect::Default],
    },
    TextAttributes {
        start: 51,
        end: 55,
        effects: vec![TextEffect::Animated(Animation::Big)],
    },
    TextAttributes {
        start: 55,
        end: 60,
        effects: vec![TextEffect::Animated(Animation::Small)],
    },
    TextAttributes {
        start: 60,
        end: 61,
        effects: vec![TextEffect::Default],
    },
    TextAttributes {
        start: 61,
        end: 66,
        effects: vec![TextEffect::Animated(Animation::Shake)],
    },
    TextAttributes {
        start: 66,
        end: 67,
        effects: vec![TextEffect::Default],
    },
    TextAttributes {
        start: 67,
        end: 70,
        effects: vec![TextEffect::Animated(Animation::Nod)],
    },
    TextAttributes {
        start: 70,
        end: 71,
        effects: vec![TextEffect::Default],
    },
    TextAttributes {
        start: 71,
        end: 78,
        effects: vec![TextEffect::Animated(Animation::Explode)],
    },
    TextAttributes {
        start: 78,
        end: 79,
        effects: vec![TextEffect::Default],
    },
    TextAttributes {
        start: 79,
        end: 85,
        effects: vec![TextEffect::Animated(Animation::Ripple)],
    },
    TextAttributes {
        start: 85,
        end: 86,
        effects: vec![TextEffect::Default],
    },
    TextAttributes {
        start: 86,
        end: 91,
        effects: vec![TextEffect::Animated(Animation::Bloom)],
    },
    TextAttributes {
        start: 91,
        end: 92,
        effects: vec![TextEffect::Default],
    },
    TextAttributes {
        start: 92,
        end: 98,
        effects: vec![TextEffect::Animated(Animation::Jitter)],
    },
])]
```
